apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-cm
  namespace: {{ .Values.namespace }}
data:
  elasticsearch.yml: |
    http.port: 9200
    network.host: 0.0.0.0
    transport.host: localhost
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch-dm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      volumes:
      - name: "elasticsearch-config"
        configMap:
          name: elasticsearch-cm
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        ports:
          - containerPort: 9200
        volumeMounts:
          - name: "elasticsearch-config"
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
