apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-cm
data:
  elasticsearch.yml: |
    http.port: 9200
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    network.host: 0.0.0.0
    transport.host: localhost
    transport.tcp.port: 9300
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch-dm
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      volumes:
      - name: "elasticsearch-config"
        configMap:
          name: elasticsearch-cm
      containers:
      - name: elasticsearch
        image: elasticsearch:7.13.0
        ports:
          - containerPort: 9200
          - containerPort: 9300
        volumeMounts:
          - name: "elasticsearch-config"
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
