apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-cm
  namespace: {{ .Values.namespace }}
data:
  kibana.yml: |
    server.host: 0.0.0.0
    elasticsearch.hosts: "localhost:9200"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kibana-dm
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      volumes:
      - name: "kibana-config"
        configMap:
          name: kibana-cm
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.1
        ports:
          - containerPort: 5601
        volumeMounts:
          - name: "kibana-config"
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
