apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-cm
data:
  kibana.yml: |
    server.host: 0.0.0.0
    elasticsearch.hosts: ["http://elasticsearch-svc:9200"]
    monitoring.ui.container.elasticsearch.enabled: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kibana-dm
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      volumes:
      - name: "kibana-config"
        configMap:
          name: kibana-cm
      containers:
      - name: kibana
        image: kibana:7.13.0
        ports:
          - containerPort: 5601
        volumeMounts:
          - name: "kibana-config"
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
