apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - name: port-defaults
      port: 5601
      targetPort: 5601
      nodePort: 31605
