apiVersion: v1
kind: Service
metadata:
  name: logstash-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: logstash
  type: NodePort
  ports:
    - name: port-get-logs
      port: 5044
      targetPort: 5044
      nodePort: 31288
